version: '3'

services:
  graal-postgres:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: graal-postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    ports:
      - 5442:5432
    deploy:
        resources:
            limits:
              cpus: "1.0"
              memory: "8192M"
            reservations:
              cpus: "1.0"
              memory: "8192M"
volumes:
    postgres-data:
        driver: local